on: [push]

name: Azure/CLI - the actual repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.SPN }}

    - name: Azure cli
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az account show
          az aks list
