on:
  issues:
    types: [opened, edited, milestoned]

name: Azure/CLI - the actual repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.SPN }}

    - name: Checkout                                                                    
      uses: actions/checkout@v1
      
    - name: Azure cli
      uses: azure/CLI@v0-beta
      with:
        azcliversion: 2.0.76
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/script.sh |
          $GITHUB_WORKSPACE/script.sh anurag
