on: [push]

name: Azure/CLI - the actual repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.SPN }}

    - run: |
        az account show 
