on: [push]

name: Azure/CLI - the actual repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.SPN }}

    - name: Create ACR
      id: create-acr
      run: |
       echo "::set-output name=username::`az acr credential show -n anu123acr --query username`"
       
    - run: |
        echo ${{ steps.create-acr.outputs.username }}
      
        
        
